produtosJson = [
    {
        id:1,
        name: 'WIFI PINEAPPLE',
        img: 'IMG/Bolsa de couro preta 1.jpg',
        hover: 'IMG/Bolsa de couro preta 2.jpg',
        price: 100000,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:2,
        name: 'Flipper Zero',
        img: 'IMG/Bolsa de couro 1.jpg',
        hover: 'IMG/Bolsa de couro 2.jpg',
        price: 250000,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:3,
        name: 'HACKRF ONE',
        img: 'IMG/Deskmat 1.jpg',
        hover: 'IMG/Deskmat 2.jpg',
        price: 130000,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:4,
        name: 'Deauth Watch',
        img: 'IMG/kit 1.jpg',
        hover: 'IMG/kit 2.jpg',
        price: 70000,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:5,
        name: 'USB Rubber Ducky',
        img: 'IMG/bota preta 1.jpg',
        hover: 'IMG/bota preta 2.jpg',
        price: 45000,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:6,
        name: 'Curso 1',
        img: 'IMG/1.jpeg',
        hover: 'IMG/1.jpeg',
        price: 259,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:7,
        name: 'Coffee',
        img: 'IMG/2.jpg',
        hover: 'IMG/2.jpg',
        price: 35,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:8,
        name: 'Notebook',
        img: 'IMG/3.jpeg',
        hover: 'IMG/3.jpeg',
        price: 32,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    {
        id:9,
        name: 'Wallet',
        img: 'IMG/4.jpg',
        hover: 'IMG/4.jpg',
        price: 85,
        desc: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt officiis corporis mollitia eos maiores illo facere sint iusto, distinctio facilis molestias ducimus debitis quas veniam fuga vitae porro. Minima, iusto?' ,
    },
    
]
